### ISSUE TITLE
GitHub API Error (rate limit) when too many commits are fetched

### ISSUE THREAD

**Issue by ocervell** [googleapis/release-please#1068]
We tried setting up release-please on this repo (https://github.com/openfoodfacts/openfoodfacts-server), but since the repo is very active the tool tries to fetch hundreds of commit, exceeding the API rate limit...

Check https://github.com/openfoodfacts/openfoodfacts-server/runs/3676514657?check_suite_focus=true

**Comment by chingor13** [comment]
I think the issue here is that the repo has never had any releases (tags) so our code will try to start from the beginning of time to collect commits to include in the CHANGELOG. For this repo it's like 30k commits which will blow through quota.

I'm adding a command line option in #1070 which will let you tell release-please what the last release was. In this case you could pick some SHA in history and assign it a previous version (0.0.0 maybe?)

**Comment by ocervell** [comment]
@chingor13 that would be perfect !

**Comment by chingor13** [comment]
This was released in https://github.com/googleapis/release-please/releases/tag/v12.3.0

An example of running the CLI command is in #1070

You'll likely want to run the CLI command as a one-off for the first release, then future releases either the GitHub action or GitHub app will find the first release.
