### ISSUE TITLE
Manifest releaser: Customize PR title

### ISSUE THREAD

**Issue by phated** [googleapis/release-please#1072]
**Is your feature request related to a problem? Please describe.**
When using the Manifest releaser, the PR title is always `chore: release main`. It seems like the PR title is configurable for the non-Manifest releaser. We'd like to customize the title of our PRs in a similar fashion.

 **Describe the solution you'd like**
It'd be ideal to specify a PR title format in the release-please manifest file.

 **Describe alternatives you've considered**
I've also considered writing a custom workflow that updates the PR title after release-please runs.

 **Additional context**
Here's a Grain release PR: https://github.com/grain-lang/grain/pull/872 - Notice that we have to remember to update the title to `chore: Release Grain vX.X.X` before we merge.

**Comment by chingor13** [comment]
This is probably possible to add an option like `pull-request-title-pattern` for the manifest itself.

We would only be able to inject the version if there is a configured root component (path of `.`), otherwise we wouldn't know which component to pick (and it would not necessarily be in every release).

**Comment by phated** [comment]
@chingor13 Maybe we can make it an option on the `"."` path? That's what we use currently.
