### ISSUE TITLE
Add support for pnpm

### ISSUE THREAD

**Issue by shivjm** [googleapis/release-please#1098]
**Is your feature request related to a problem? Please describe.**
I’d like to be able to use this with a Node monorepo, but because it uses [pnpm](https://pnpm.io/), release-please isn’t able to update the versions of dependent packages.
 **Describe the solution you'd like**
I would like release-please to understand the pnpm-lock.yaml format and [pnpm workspaces](https://pnpm.io/workspaces).
 **Describe alternatives you've considered**
What I’ll be doing now is writing a fragile and tedious workflow myself to handle what release-please would do, in a more manual and opaque fashion.

**Comment by daton89** [comment]
I've had this issue because pnpm needs to have the `workspace:*` in the version in order to understand that a dependency is a package to link in the current workspace. But currently the node-workspace plugin doesn't support that format so it is not possible to use release please in a pnpm workspace. 
https://github.com/daton89/pnpm-nx-release-please/runs/7508377181?check_suite_focus=true

**Comment by Himself65** [comment]
My workaround is to use `*` and use alias in tsconfig.json

**Comment by nahsi** [comment]
@chingor13 pnpm is not working still.
