### ISSUE TITLE
release-please fails to find existing release for Node.js, results in 422

### ISSUE THREAD

**Issue by bcoe** [googleapis/release-please#1125]
## Problem

release-please is failing to find an existing pull request for yargs/yargs, this results in a 422 error when it attempts to create a branch that already exists (gist available upon request).

## Reproducing

`node ./build/src/bin/release-please.js release-pr --release-type=node --token=$GITHUB_TOKEN --repo-url=yargs/yargs`

**Comment by chingor13** [comment]
That's odd - code-suggester does the branch creation and pull request opening and we use `force: true` to force push.

**Comment by chingor13** [comment]
Can you extract the validation error message?

**Comment by chingor13** [comment]
Oh, I think this is actually the same error as #1024. With the current option, it's trying to create the branch as `release-please/branches/main` when a `release-please/branches/main/components/yargs` exists. Due to the way git works, it treats branches names as file paths and this causes naming collisions.

We should consider using a different branch name delimiter.
