### ISSUE TITLE
manifest: redundant changelog for unchanged packages

### ISSUE THREAD

**Issue by axieum** [googleapis/release-please#1249]
#### Environment details

  - `release-please` version: `13.4.2`
  - `release-please-action` version: `v3.1.0`

#### Steps to reproduce

  1. Here is the PR that is duplicating the changelog for unchanged packages (that have `"skip-github-release": true`)
  https://github.com/axieum/fabric-release-please/pull/25

**Comment by chingor13** [comment]
The `skip-github-release` option only absolves `release-please` of its duty to handle the tagging of releases on GitHub. It still needs to know what the SHA of the last release of that component was (so we can determine commits since last release).

Without releases/tags, it's inefficient to try to keep iterating through history searching for a component that is never tagged. It is possible that we could add this fallback logic however.
