### ISSUE TITLE
release-please(java): missing snapshot PRs

### ISSUE THREAD

**Issue by kolea2** [googleapis/release-please#1253]
I'm currently looking for snapshot PRs to be generated for the following (non main) branches:
https://github.com/googleapis/java-bigtable-hbase/tree/1.20.0-sp
https://github.com/googleapis/java-bigtable-hbase/tree/1.25.2-sp
https://github.com/googleapis/java-bigtable-hbase/tree/bigtable-1.x

I tried running the force run label and still no luck.

**Comment by kolea2** [comment]
hi @chingor13, I'm still not seeing snapshot PRs for any of the branches listed. Can you take a look? Thanks!

**Comment by chingor13** [comment]
It was fixed in Jan 24, but there haven't been any events to those branches to retrigger the creation of the PRs. Adding a `release-please:force-run` label to a PR triggers release-please for the base branch of that PR -- so I added the label to the latest release PR for those 3 branches and the snapshot PRs were created.

Moving forward, this should not be necessary any more.

**Comment by kolea2** [comment]
Thank you!
