### ISSUE TITLE
Spurious version bumps for workspace dependencies in cargo workspace

### ISSUE THREAD

**Issue by CBenoit** [googleapis/release-please#1407]
Similar to https://github.com/googleapis/release-please/issues/1403, but opening another issue because I'm not sure the root cause is identical.

- `release-please` version: 13.14.0
- Example: https://github.com/CBenoit/my-gh-actions-playground/pull/2
- [Link to repository after merging](https://github.com/CBenoit/my-gh-actions-playground/tree/b-v0.3.0)

#### Steps to reproduce

  1. Start with an initial monorepo containing a cargo workspace of two crates A and B.
  2. Make B depends on A by updating `B/Cargo.toml`.
  3. Push a `feat` commit for crate B only.
  4. Observe the issue.
    a. **A also have a patch version bump in the release PR, but with no change**, and a changelog consisting of a 'Dependencies' header and an empty body.
    b. **`.release-please-manifest.json` is NOT updated with the minor bump of B, resulting in a mismatch between the manifest and the reality.**
    c. The PR body is referring to A using the default package name instead of the one specified in `release-please-config.json` (if any)

**Comment by chingor13** [comment]
This looks unrelated, but definitely a bug. We are building a dependency graph, the traversing over each component and either finding a candidate release version or bumping the version. It should be bumping only components that need to be bumped.

**Comment by chingor13** [comment]
After some digging, this is happening because we [default `updateAllPackages` to be true](https://github.com/googleapis/release-please/blob/2a63ea2b5791f79b065398c1c4ed1b63258e781b/src/plugins/cargo-workspace.ts#L93) for the cargo-workspace plugin. I'm unsure why this is the case. Without that configuration, it should only version bump components that depend on components being updated.
