### ISSUE TITLE
Manifest releaser always releases every package regardless of changes

### ISSUE THREAD

**Issue by axieum** [googleapis/release-please#1527]
Hi, 👋

#### Summary

It appears that packages (in the manifest) are always being released, regardless of whether their contents were edited or not. I believe the packages that haven't changed are inheriting the root package's version and being re-released?

#### Environment details

  - OS: Ubuntu 20.04.4 LTS (20220710.1)
  - Node.js version: -
  - npm version: -
  - `release-please` version: 13.18.7
  - `release-please-action` version: v3.2.8 (SHA: b910fcea1279e7744f01ca9c82f79502240ccf7c)

#### Steps to reproduce

  1. Make a change to one of the packages defined in the Manifest
  2. Merge the proposed pull-request
  3. Notice `release-please` create a new release for every package, not just those that changed

Affected pull request: https://github.com/axieum/minecord-rp-test/pull/2
Affected GitHub Actions run: https://github.com/axieum/minecord-rp-test/actions/runs/2682112305

Please find the GitHub Actions run logs here: [logs_6.zip](https://github.com/googleapis/release-please/files/9125991/logs_6.zip)

Thanks,
Jonathan.

**Comment by chingor13** [comment]
Sorry for the slow response on this issue.

What's happening is that commits are filtered by component path (the core is not smart enough to understand to exclude other components' paths). So the root component (`.`) is seeing the bugfix for your `chat` component.

It could be possible to add an option as a feature request that would have the commit splitter ignore commits that are in other modules. We do want to keep the current behavior as the default because often folks will use this repository structure to release a root component which is a meta-package of all the subpackages and which does want to version bump if any of its subpackages is version bumped.

**Comment by axieum** [comment]
Hi @chingor13,

What you've described sounds correct, but it appears it's also bumping unchanged sub-packages when the root component changes?

> release a root component which is a meta-package of all the subpackages and which **does** want to version bump if any of its subpackages is version bumped.

I'd expect other sub-package versions' to **not** be affected by different sub-package changes, however?

In the example I've posted, I have the following project layout:

* `.`
* `minecord-api/`
* `minecord-chat/`
* `minecord-cmds/`
* ...

When I make a change to the `minecord-chat/` component, it generates the pull request (axieum/minecord-rp-test#2) **correctly**, however, after merging said pull-request it goes ahead and releases more than the PR mentioned. It released `.` and `minecord-chat/` correctly, but then the unchanged sub-packages were also re-released with the `.` version.

If I find time soon, I might try to clone release-please and step through the debugger to identify why it's bumping unchanged components.

**Comment by chingor13** [comment]
Ok, the 5 tagged releases totally looks like a bug. It should be parsing the release notes to know which components to tag and at what versions.

**Comment by daton89** [comment]
I'm having the same issue and after a long investigation I've casually noticed that this issue happens when you include a custom pr title pattern with the version of the `.` package. Apparently all the packages will be tagged with that "root" version and release-please probably doesn't find the correct tag for the packages. I can provide a repo to reproduce this issue if this can help.
