### ISSUE TITLE
`label` and `release-label` for each packages are ignored

### ISSUE THREAD

**Issue by mshrtsr** [googleapis/release-please#1624]
I configured `label` and `release-label` for each packages, but it is not reflected in to release PR.

I think it is a bug because [the JSON Schema of the config](https://github.com/googleapis/release-please/blob/main/schemas/config.json) allows `label` or `release-label` inside packages.
However, I'm sorry if it is correct behavior.

An example of my `release-please-config.json` follows:
```json
{
  "separate-pull-requests": true,
  "packages": {
    "packages/a": {
      "label": "autorelease: pending,Package-A",
      "release-label": "autorelease: tagged,Package-A",
    },
    "packages/b": {
      "label": "autorelease: pending,Package-B",
      "release-label": "autorelease: tagged,Package-B",
    }
  }
}
```

#### Environment details

  - OS: macOS
  - Node.js version: v16.11.0
  - npm version: 8.0.0
  - `release-please` version: 13.21.0

#### Steps to reproduce

  1. configure release-please-config.json with `label` or `release-label` properties in `packages`
  2. run `release-please release-pr` to create a release PR

=> The created release PR does not have the labels specified in the config.

#### Root cause

The ReleaserConfig has `labels` and `releaseLabels` properties on the type definition,

https://github.com/googleapis/release-please/blob/3169b4331ddad030a528cfc4003b5fef04ca8588/src/manifest.ts#L95

but `mergeReleaserConfig()` doesn't return then.

https://github.com/googleapis/release-please/blob/3169b4331ddad030a528cfc4003b5fef04ca8588/src/manifest.ts#L1508

**Comment by chingor13** [comment]
I think this was an oversight in building these configs. The `label` and `release-label` fields were intended to be load-bearing state labels so that release-please can identify it's pull requests.

I see 2 options here:

1. adjust the handling of the per-component labels so that it reads from the component configs (like most other options)
2. make `label` and `release-label` fields on the root manifest (not per-component) and introduce a new `extra-labels` option

For (1), the downside is that you have to repeat the desired label in both `label` and `release-label` and for each component.

For (2), the downside is having an additional config option to maintain. An example config:
```json
{
  "separate-pull-requests": true,
  "packages": {
    "packages/a": {
      "extra-label": "Package-A"
    },
    "packages/b": {
      "extra-label": "Package-B"
    }
  }
}
```

In either case, we probably need to fix the merge logic when combining pull requests to include all labels of the merged component pull requests. So if in your example you skipped the `separate-pull-requests` option, then the resulting pull request would have 3 labels: `autorelease: pending`, `Package-A` and `Package-B`.

**Comment by mshrtsr** [comment]
@chingor13 
Sorry for the late response.

I think (2) is better because the main purpose of `label` `release-label` and `extra-label` looks different.
- The `label` and `release-label` fields are referenced by release-please
- The `extra-label` is referenced by users, other CI/CD pipelines, and so on.

 > The `label` and `release-label` fields were intended to be load-bearing state labels so that release-please can identify it's pull requests.
