### ISSUE TITLE
Python version is never released

### ISSUE THREAD

**Issue by Nickersoft** [googleapis/release-please#1801]
Hey folks,

Wasn't sure whether to file a bug for this, or if it is user error on my part – I'm currently using release-please in my monorepo, which contains a [Python project using Poetry](https://github.com/TheOpenDictionary/odict/tree/main/python). I have a pyproject.toml, but no setup files, as they aren't really needed. I noticed that release-please is capturing these changes under a semantic [version in my PRs](https://github.com/TheOpenDictionary/odict/pull/87) (the Python library is 0.0.13 in this specific PR), _however_, upon merging the PR a release is never created, and the [deployment action](https://github.com/TheOpenDictionary/odict/blob/main/.github/workflows/release-please.yml#L43-L44) never runs. I've tried re-running release-please as recommended in the docs, but to no avail. My changes have kept piling up, so now release-please has grouped about 5 releases worth of changes under this single Python release.

Is this happening solely because I don't have setup files in my repo, or is there possibly a bug at play here? Any help would be appreciated!

**Comment by chingor13** [comment]
Sorry for the delay in getting to this. Try giving each of the configured components a "component" name which is used as a prefix for the release tag. I think release-please is getting confused because you have multiple releases that are all trying to use the same git tags (plain semver) rather than splitting by type.

I would expect your repo to have tags like `js-v0.0.5`, `python-v0.1.0`, `jvm-0.0.1` and a plain `v1.8.5` (for the root component).

**Comment by Nickersoft** [comment]
Yay your suggestion worked!! I had suspected maybe it was confused because of the identical package names. Adding a `component` field to the package configs worked. Sorry it took me a little while to circle back to this. Gonna close this.
