### ISSUE TITLE
Python pyproject.toml with dynamic version

### ISSUE THREAD

**Issue by mwtoews** [googleapis/release-please#1804]
PR #894 added support for pyproject.toml files to support some aspects of [PEP 621](https://peps.python.org/pep-0621/) for project metadata, as supported by Poetry, Flit and Setuptools. However, release-please will raise "✖ invalid pyproject.toml" with the following:
```toml
[project]
name = "my_package"
dynamic = ["version"]
```
this is because "version" is intentionally unspecified so another tool can/will provide such metadata dynamically, e.g. [python-versioneer](https://github.com/python-versioneer/python-versioneer) or [setuptools_scm](https://github.com/pypa/setuptools_scm/).

This manifests itself in a puzzling issue raised with this change https://github.com/snakemake/snakemake/pull/2065 where versioneer is upgraded and setup.cfg is removed. A previous change https://github.com/snakemake/snakemake/pull/2026 did not raise any issue with please-release, and it's not clear why. (I'm running https://github.com/nektos/act locally, but am unable to re-create the initial success, I only see "invalid pyproject.toml" due to the missing "version" item). This is considered a bug because it worked before swapping core metadata to pyproject.toml for this project.

How to proceed? Perhaps it should be prioritised trying to fetch the version from `__version__` in `my_package/__init__.py`?

**Comment by chingor13** [comment]
I am unfamiliar with versioneer or other ways to specify a version in a python package. Does it fetch the version from the git tag at publish time?

I think we can simply [remove the thrown error](https://github.com/googleapis/release-please/blob/fe3a979a1c228610612aa2d6c303d408be956e2e/src/updaters/python/pyproject-toml.ts#L54-L58) and convert the error message to a warning if there is no version field in the toml file.

**Comment by mwtoews** [comment]
Apologies in the delay. Versioneer or other tools evaluate the version from usually git tags, e.g. `git describe --tags`. I'm investigating a build-system independent method to get the package version. I'll update as soon as I get a better idea.

**Comment by lukedyer-peak** [comment]
The issue is with release-please grabbing the dynamic `version` from the correct place.  Official python packaging [docs](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dynamic) leave the option for where it should live open to the build backend.  Some backends allow users to specify exactly where it should live (eg [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata)) others [flit](https://flit.pypa.io/en/stable/pyproject_toml.html#new-style-metadata) assume it'll be in the more conventional place of `__init__.py:__version__`.  I believe, most usual case for `release-please` would be to still look for `__version__` in __init__.py`.  It would also be a good fallback place to look if it can't be determined (easily) from `pyproject.toml`

Note from PEP 621 docs:
> This PEP [621] is a historical document. The up-to-date, canonical spec, [Declaring project metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata), is maintained on the [PyPA specs page](https://packaging.python.org/en/latest/specifications/).

**Comment by albjoaov** [comment]
> I am unfamiliar with versioneer or other ways to specify a version in a python package. Does it fetch the version from the git tag at publish time?
> 
> I think we can simply [remove the thrown error](https://github.com/googleapis/release-please/blob/fe3a979a1c228610612aa2d6c303d408be956e2e/src/updaters/python/pyproject-toml.ts#L54-L58) and convert the error message to a warning if there is no version field in the toml file.

🆙 on this

**Comment by rickstaa** [comment]
Implemented in https://github.com/googleapis/release-please/pull/1983.
