### ISSUE TITLE
Rewrite changelog entries

### ISSUE THREAD

**Issue by rsenden** [googleapis/release-please#1901]
Suppose a lot of new features/fixes/... have been merged to the `main` branch, release-please has created a PR with a long changelog, but this PR hasn't been merged yet (i.e., we're still working on additional features/fixes/...).

Now suppose that we've identified a problem with one of the previously merged fixes/features, and need to either remove or update the feature/fix. This means that the previously generated changelog entry either needs to be removed, or may need to be updated to reflect the new changes; we wouldn't want to have two changelog entries with one describing the old behavior and another one describing the updated behavior.

What would be the best way to accomplish this with release-please, other than rewriting the commit history? For example, is there any possibility to have a new commit message override features/fixes mentioned in an older commit message? I'm not sure whether https://github.com/googleapis/release-please#how-can-i-fix-release-notes is appropriate for this use case?

**Comment by chingor13** [comment]
If you are using pull requests (you probably should be), then the `BEGIN_COMMIT_OVERRIDE` feature is what you want to use. When release-please finds the commit, it looks at the PR that created it and the PR body has the commit override annotation, then it will treat that content as the commit message rather than what was actually put as the commit message. We do this all the time when we erroneously merge a PR with the wrong commit type or a typo. Note that you need to re-run release-please (however you are running it -- app, GitHub actions, CLI) to have it look at the new commit message.

Alternatively, you can rewrite the commit history and force-push (but we do not recommend that approach).

**Comment by rsenden** [comment]
Thanks for the reply. In our case, we'd want to update a changelog entry that was generated by a PR that was already merged. I was assuming that `BEGIN_COMMIT_OVERRIDE` could only be used before merging the PR, to override the original commit messages when you are merging the PR. However, I guess we can still update the body of the PR after it has been merged/closed, and then release-please will find the `BEGIN_COMMIT_OVERRIDE` on the next run, correct? Maybe it would be good to mention this more explicitly in the release-please documentation?
