### ISSUE TITLE
Question: search depth limitation

### ISSUE THREAD

**Issue by alex-enchi** [googleapis/release-please#1903]
Hi
I have noticed that no matter how fresh latest release is, release-please always checks last 500 (default) commits.

Is it mandatory behaviour? Or it is possible to fetch commits after latest release?

In my case run of release-please takes around 2 minutes no matter how big release is (even if it just one small fix added to one of the packages)

**Comment by chingor13** [comment]
Are you letting release-please tag the releases? How is your repository configured (manifest or programatically via GitHub actions/app inputs)?

Release-please tries needs to find the commit SHA of the latest release. Using a manifest config is usually the most efficient, because the manifest tells release-please what the expected last version is -- it then needs to find the SHA of that release version. Without the manifest, we paginate backwards through commits to try and guess what the last release was.

**Comment by alex-enchi** [comment]
I am using manifest, and have a "root" package with multiple packages underneath. Only root gets released via release-please but everything gets tagged and that release commit is captured by release-please according to logs.
But it still goes further away in history by some reasons.
Will check or at least do a reproduction repository to demo the issue.

**Comment by alex-enchi** [comment]
For my release process I have 1 root release with tags `@root-v1.2.3`, `@package-foo-v1.2.3`, `@package-bar-v1.2.3` and 0 packages github releases. And in the case it finds github release, it finds all the tags but does not go out from the iterator [here](https://github.com/googleapis/release-please/blob/main/src/manifest.ts#L617-L620)
because `needsBootstrap` is true since it consider only github releases and not tags

Here is the small fix #1915
