### ISSUE TITLE
Add normal dotnet strategy

### ISSUE THREAD

**Issue by HaakonSvane** [googleapis/release-please#2217]
**Is your feature request related to a problem? Please describe.**
It seems there is little support for normal dotnet projects. The dotnet-yoshi strategy seems to require an (undocumented) apis/apis.json file to work, but versioning should instead follow best practices (probably need an expert on dotnet versioning to chime in here).

 **Describe the solution you'd like**
An easy dotnet strategy option that does not require custom files and adheres to industry standards for versioning.

 **Describe alternatives you've considered**
The dotnet-yoshi strategy is undocumented (?) and requires a `apis/apis.json` file.

**Comment by calebkiage** [comment]
The simple strategy works with dotnet. Just add the csproj file to the `extra-files` section [as shown here](https://github.com/googleapis/release-please/blob/72b0ab360c3d6635397e8b02f4d3f9f53932e23c/docs/customizing.md#updating-arbitrary-xml-files)

**Comment by chingor13** [comment]
As far as I could tell, there is no canonical way in .NET to specify the version number (unlike something like nodejs which has a spec for package.json where the version number should go). The *-yoshi strategies are undocumented because we were using them for our bespoke repository setups and do not want to broad usage (we can make breaking changes to them without notice).

If there is a canonical way that .NET repositories are structured, then we can certainly entertain building a generic `dotnet` strategy. 

> The simple strategy works with dotnet. Just add the csproj file to the `extra-files` section [as shown here](https://github.com/googleapis/release-please/blob/72b0ab360c3d6635397e8b02f4d3f9f53932e23c/docs/customizing.md#updating-arbitrary-xml-files)

This is the way to go. A csproj file is an XML document and you can update whichever attribute you want.

**Comment by ricardoboss** [comment]
Hi, I was looking for exactly this feature and wanted to provide my point of view on this.

I would argue there is a canonical way that .NET projects specify versions. Actually, there are [many](https://gist.github.com/jonlabelle/34993ee032c26420a0943b1c9d106cdc). Based on the assumption that only one way is needed for most use cases (`PackageVersion` for NuGet packages), it's probably viable to provide a strategy `dotnet-package` that updates the `<PackageVersion>1.0.0</PackageVersion>` property in `.csproj` files.

What do you think?
