### ISSUE TITLE
How does this compare to semantic-release?

### ISSUE THREAD

**Issue by trusktr** [googleapis/release-please#454]
Just curious how release-please compares to [semantic-release](https://github.com/semantic-release/semantic-release).

**Comment by bcoe** [comment]
Hey @trusktr 👋 , there is quite a bit of overlap between semantic-release and release-please in functionality:

* semantic-release can be configured to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), release-please uses Conventional Commits only.
* there's a lot of shared tooling (in [conventional changelog](https://github.com/conventional-changelog/conventional-changelog)).

The major differences are:

1. release-please creates a candidate release PR, rather than always releasing what is on the main branch.
2. release-please has a variety of custom release workflows that were required by our team (for instance supporting our custom mono-repos).

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
