### ISSUE TITLE
Add support for python repositories with a pyproject.toml

### ISSUE THREAD

**Issue by jtpavlock** [googleapis/release-please#515]
**Is your feature request related to a problem? Please describe.**
I have a python repository managed with [poetry](https://github.com/python-poetry/poetry) that I'd like to use release-please with.
 **Describe the solution you'd like**
Support for pyproject.toml defined python repositories.
 **Describe alternatives you've considered**
Dropping poetry support for my project, which isn't really something I'd like to do in order to use release-please.
 **Additional context**
None

**Comment by ygworldr** [comment]
[I just opened this…](https://github.com/google-github-actions/release-please-action/issues/287)

I know nothing about TS and sadly have no time to try but I think it should not be much work to copy the current one and just change the filenames. I am happy to test any PR.

@jtpavlock It has been a while since you posted this, did you come up with any alternatives?

**Comment by Mesteery** [comment]
I'll take care of it! :+1:
