### ISSUE TITLE
support releasing at a specific commit

### ISSUE THREAD

**Issue by codyoss** [googleapis/release-please#879]
**Is your feature request related to a problem? Please describe.**

Sometimes a maintainer does not want to release all of the changes on HEAD. For examples a person might land an import bug fix and then a small feature request after. It would be nice if release-please could target a commit release all changes up to that point. So in this example target the bug fix and not include the feature.

 **Describe the solution you'd like**

Honor a comment command on the PR to set the commit where release-please should stop processing. Example `/targetCommit someHash`.

 **Describe alternatives you've considered**

Support only from the CLI mode.

**Comment by chingor13** [comment]
I think you can do this already assuming you are doing this as a one-off and not automated process.

Consider the following git history:

```
[aaaaaa] chore: release 1.2.3
[bbbbbb] fix: some bugfix
[cccccc] feat: some feature
```

You can create a new "release branch" and target it for the release.

```
# create a new branch from the target bugfix
git checkout bbbbbb
git checkout -b 1.2.3-bugfix
git push -u origin 1.2.3-bugfix

# run release-please against the new bugfix branch
release-please release-pr \
  [other args]
  --default-branch=1.2.3-bugfix  
```

This will open a release PR against your 1.2.3-bugfix branch and only see the commit history on that branch. In this case, it will see commit `bbbbbb` as the only releasable commit since the last release `aaaaaa`.

**Comment by codyoss** [comment]
Thanks @chingor13 this is good enough for my use case. It might be nice to have use-cases like this documented in a wiki or readme. Closing as it seems like the behavior is supported well enough.
