### ISSUE TITLE
Other PR Workflows not run on release-please PRs using the GitHub action

### ISSUE THREAD

**Issue by jthegedus** [googleapis/release-please#922]
My repo has some Required Status Checks for GitHub Actions which run tests, linting etc. These are required for all PRs. The triggers for these workflows is `pull_request`.

The PR created by `release-please` does not trigger the Actions which should trigger for all PRs.

- why is this?
- is this solvable on my end?
- is it solvable as a configuration to `release-please`?

This is the repo and an example PR - https://github.com/jthegedus/asdf-gcloud/pull/47

---

I searched this repo, the `please-release-action` repo and Google for an answer. The only related question on this topic I could find was this https://github.com/googleapis/release-please/issues/766#issuecomment-777993157 which had a reply which does not seem to apply or I do not understand how it should apply.

**Comment by SurferJeffAtGoogle** [comment]
I see 
![image](https://user-images.githubusercontent.com/11778530/120562847-18aa1600-c3bc-11eb-91dd-5576a955edce.png)

Have you seen this behavior more than once?
@bcoe Any ideas?

**Comment by jthegedus** [comment]
I have experienced this behaviour on all `release-please` PRs. I have only been a user a few days as I test before integrating into large repos. This is one requirement.

**Comment by jthegedus** [comment]
Additional information, here are my Branch Protection settings:

![image](https://user-images.githubusercontent.com/20798510/121444530-10149980-c9d3-11eb-875e-27f082ca23d0.png)

**Comment by atreya2011** [comment]
My understanding is that GitHub actions got cannot trigger another GitHub action. For now I am using my personal access token so the PRs are opened by me thereby triggering the required workflows.

**Comment by jthegedus** [comment]
> My understanding is that GitHub actions got cannot trigger another GitHub action. For now I am using my personal access token so the PRs are opened by me thereby triggering the required workflows.

Thanks for pointing this out.

The docs for that are:
- [GitHub Docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)
- [Release Please docs (first item in table)](https://github.com/google-github-actions/release-please-action#configuration)

The fix for my `release-please` workflow is:

```diff
name: Release-Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
+         token: ${{ secrets.CUSTOM_PAT_WITH_WORKFLOWS_ACCESS }}
```

Which results in:

![image](https://user-images.githubusercontent.com/20798510/121991244-a33e3c80-cde2-11eb-8378-654e748761af.png)

This aspect of GitHub actions is unfortunate for large projects because the release then relies on a maintainer's PAT or they must create a Bot account to manage the PAT in a user-independent way.

A suggestion would be to include a line in the Actions docs or docs here to indicate using a custom PAT will:

1. allow the `release-please` PR to trigger workflows on it's PR
2. opens users up to recursive workflow executions (which is why the default GITHUB token does not trigger workflows on Bot events)

**Comment by atreya2011** [comment]
@jthegedus 

So after a bit of experimenting, I found a creative way to get release-please to play nicely without using a personal access token and here is what I did. 
I was experimenting with `go` but this should work for other release types as well.

1. I installed the `release-please` bot found here: https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please
2. Added the following `release-please.yml` configuration file under the `.github` directory
```yaml
primaryBranch: main
releaseType: go
```
Creating the above file ensure that the bot opens a release PR. And since the bot (not GitHub actions) opens the PR, the status checks should run normally.
I couldn't test this because I don't have a Pro account. However, I confirmed that GitHub actions were triggered when the bot's release PR was opened.

3. Then I created another `release-please.yml` in the `.github/workflows` directory with the following

```yaml
on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        continue-on-error: true
        with:
          release-type: go
          command: github-release
```

I specifically set `command: github-release` and `continue-on-error: true` so that the workflow doesn't fail and only Github releases are created.
This way the bot creates the PR and Github actions creates the release.

**Comment by chingor13** [comment]
Apologies for the lack of response on this issue. It looks like you found the GitHub app.

You can additionally add the `handleGHRelease: true` to the `.github/release-please.yml` and it should be able to handle the GitHub release tagging functionality.

**Comment by chingor13** [comment]
Re-triaging this as a documentation issue - the GitHub actions limitation is not something we can fix. In this case you need to either:
1. use a personal access token in the release-please-action
2. use the app (which is not an officially supported service, but our team uses it)

**Comment by jthegedus** [comment]
Thanks for the further discussion. As I understand now, the underlying package used by `release-please` action has the ability (including configuration) to itself create the PR and GitHub Release?

@chingor13 would exposing this package functionality to the Action not circumvent the action limitations?

**Comment by atreya2011** [comment]
> Apologies for the lack of response on this issue. It looks like you found the GitHub app.
> 
> You can additionally add the `handleGHRelease: true` to the `.github/release-please.yml` and it should be able to handle the GitHub release tagging functionality.

My apologies. I should have been more specific with regards to the example above. It seems like `handleGHRelease: true` does not work for private repositories and hence the I am using the bot to create the PR and Github actions to create the release.

https://github.com/googleapis/repo-automation-bots/issues/1636

**Comment by chingor13** [comment]
`handleGHRelease: true` is working for private repos. Please double-check if there are pending permission request for the GitHub app -- we updated the requested permissions a few months ago to have access to the code so we can read version files and create releases on private repos.

**Comment by atreya2011** [comment]
@chingor13 Thank you for your response. I double-checked the permissions given to the app and have attached the screenshot. Are there any other settings that I have to add to the YAML file to get `handleGHRelease` to work because it is still not working, unfortunately :(

![Screenshot from 2021-07-08 18-16-02](https://user-images.githubusercontent.com/44151328/124896910-cc846e00-e018-11eb-84a2-f9dfd0761c6b.png)

**Comment by remarkablemark** [comment]
My workaround was to skip the GitHub Actions workflow if the `github.actor` contains `github-actions`:

```yml
jobs:
  build:
    if: contains(github.actor, 'github-actions') == 'false'
```

See https://github.com/little-spoon-dev/design-system/pull/15
