### ISSUE TITLE
release-bot opens PR with same release version twice

### ISSUE THREAD

**Issue by Shabirmean** [googleapis/release-please#983]
_1) Is this a client library issue or a product issue?_
- This is neither a client library nor product issue. Rather the issue is pertaining to the samples repo for the **Anthos** product

_2) Did someone already solve this?_
- Seems not
 
_3) Do you have a support contract?_
- NA
---

I have a repo (https://github.com/GoogleCloudPlatform/anthos-samples) configured with the `release-please` bot. 

With one of my recent PR merges the bot has openned a release PR - https://github.com/GoogleCloudPlatform/anthos-samples/pull/73

However, a release for the version `0.2.0` _(for which the PR was opened)_ already exists: https://github.com/GoogleCloudPlatform/anthos-samples/releases

Wonder, why the bot has not bumped the version 🤔

**Comment by chingor13** [comment]
https://github.com/GoogleCloudPlatform/anthos-samples/commit/c7a4acc509e4e33c5347c4aabf729fa7300e6944 contains a `Release-As: 0.2.0` footer in the commit body. Release-please is using that version and ignoring the `Release-As: 0.3.0` commit (https://github.com/GoogleCloudPlatform/anthos-samples/commit/5868dd82a74564ae37dcd919531f42bca34636c2)

We probably need to take the last `Release-As` version if there are multiple.

**Comment by chingor13** [comment]
Update: we already do take the last `Release-As` version. What's happening here is that this repository is using the `path` configuration which pre-filters commits to only ones that have touched files in that path. The second `Release-As` commit is being ignored because it's an empty commit. The workaround is to make the `Release-As` commit and add a trivial change (e.g. whitespace to the README) to force it to be recognized.
